# Generated by Django 5.1.1 on 2024-10-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('SUV', 'Внедорожник'), ('wagon', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('coupe', 'Купе'), ('cabrio', 'Кабриолет')], default='sedan'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='white', max_length=70),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('rear', 'Задний'), ('front', 'Передний'), ('full', 'Полный')], default='rear'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')], default='gasoline'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('вариатор', 'CVT'), ('robot', 'Робот')], default='manual'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='cars_img'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_car', to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
