# Generated by Django 5.1.1 on 2024-10-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_body_type_car_color_car_drive_unit_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='cars_img'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_car', to='main.car'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
